IF NOT EXISTS (
    SELECT name 
    FROM sys.databases 
    WHERE name = N'Project'
)
BEGIN
    CREATE DATABASE Project;
END
GO

-- Bang KHOA
CREATE TABLE KHOA (
    MaKhoa VARCHAR(10) PRIMARY KEY,
    TenKhoa VARCHAR(255)
);

-- Bang NGANH
CREATE TABLE NGANH (
    MaNganh VARCHAR(10) PRIMARY KEY,
    TenNganh VARCHAR(255)
);

-- Bang BOMON
CREATE TABLE BOMON (
    MaBM VARCHAR(10) PRIMARY KEY,
    TenBM VARCHAR(255),
    MaKhoa VARCHAR(10),
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
);

-- Bang CHUYENNGANH
CREATE TABLE CHUYENNGANH (
    MaCN VARCHAR(10) PRIMARY KEY,
    TenCN VARCHAR(255),
    MaNganh VARCHAR(10),
    BoMonQL VARCHAR(10),
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh),
    FOREIGN KEY (BoMonQL) REFERENCES BOMON(MaBM)
);

-- Bang GIANGVIEN
CREATE TABLE GIANGVIEN (
    MaGV VARCHAR(10) PRIMARY KEY,
    TenGV VARCHAR(255),
    MaBM VARCHAR(10),
    MaKhoa VARCHAR(10),
    SDT VARCHAR(15),
    Email VARCHAR(255),
    FOREIGN KEY (MaBM) REFERENCES BOMON(MaBM),
    FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
);

-- Bang LOP
CREATE TABLE LOP (
    MaLop VARCHAR(10) PRIMARY KEY,
    MaCN VARCHAR(10),
    NienKhoa VARCHAR(20),
    FOREIGN KEY (MaCN) REFERENCES CHUYENNGANH(MaCN)
);

-- Bang SINHVIEN
CREATE TABLE SINHVIEN (
    MaSV VARCHAR(12) PRIMARY KEY,
    TenSV VARCHAR(255),
    MaLop VARCHAR(10),
    SDT VARCHAR(15),
    Email VARCHAR(255),
    FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
);

-- Bang HOC PHAN
CREATE TABLE HOCPHAN (
    MaHP VARCHAR(10) PRIMARY KEY,
    TenHP VARCHAR(255),
    KhoaPT VARCHAR(10),
    TinChi INT,
	FOREIGN KEY (KhoaPT) REFERENCES KHOA(MaKhoa)
);

-- Bang LOPHOCPHAN
CREATE TABLE LOPHOCPHAN (
    MaLopHP VARCHAR(10) PRIMARY KEY,
    MaHP VARCHAR(10),
    GiangVienGD VARCHAR(10),
    FOREIGN KEY (MaHP) REFERENCES HOCPHAN(MaHP),
    FOREIGN KEY (GiangVienGD) REFERENCES GIANGVIEN(MaGV)
);

-- Bang DANGKYHOCPHAN
CREATE TABLE DANGKYHOCPHAN (
    MaSV VARCHAR(12),
    MaLopHP VARCHAR(10),
    NamHoc VARCHAR(10),
    HocKy VARCHAR(10),
    PRIMARY KEY (MaSV, MaLopHP),
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV),
    FOREIGN KEY (MaLopHP) REFERENCES LOPHOCPHAN(MaLopHP)
);

-- Bang COTTP 
CREATE TABLE COTTP (
    MaHP VARCHAR(10),
    MaTP VARCHAR(10),
    TyLeTP FLOAT,
	PRIMARY KEY (MaHP, MaTP),
    FOREIGN KEY (MaHP) REFERENCES HOCPHAN(MaHP)
);

-- Bang COTDIEM
CREATE TABLE COTDIEM (
    MaCotDiem VARCHAR(10) PRIMARY KEY,
	TenCotDiem VARCHAR(10),
    MaTP VARCHAR(10),
	MaHP VARCHAR(10),
    TuanKT VARCHAR(10),
    MaPPDG VARCHAR(20),
    TenPPDG VARCHAR(255),
    NoiDungDG VARCHAR(255),
    FOREIGN KEY (MaHP, MaTP) REFERENCES COTTP(MaHP, MaTP)
);

-- Bang DIEM SINH VIEN
CREATE TABLE DIEMSINHVIEN (
    MaSV VARCHAR(12),
    MaLopHP VARCHAR(10),
    MaCotDiem VARCHAR(10),
    DiemSo FLOAT,
    PRIMARY KEY (MaSV, MaLopHP, MaCotDiem),
    FOREIGN KEY (MaSV, MaLopHP) REFERENCES DANGKYHOCPHAN(MaSV,MaLopHP),
    FOREIGN KEY (MaCotDiem) REFERENCES COTDIEM(MaCotDiem)
);

-- Bang CLO
CREATE TABLE CLO (
    MaCLO VARCHAR(10) PRIMARY KEY,
	TenCLO VARCHAR(10),
	MaHP VARCHAR(10),
    MoTaCLO VARCHAR(255),
    DoLuong VARCHAR(50),
	FOREIGN KEY (MaHP) REFERENCES HOCPHAN(MaHP)
);

-- Bang COTDIEM_CLO_MAPPING
CREATE TABLE COTDIEM_CLO_MAPPING (
    MaCotDiem VARCHAR(10),
    MaCLO VARCHAR(10),
    TyLeDapUng FLOAT,
    PRIMARY KEY (MaCLO, MaCotDiem),
    FOREIGN KEY (MaCotDiem) REFERENCES COTDIEM(MaCotDiem),
    FOREIGN KEY (MaCLO) REFERENCES CLO(MaCLO)
);

-- Bang PLO
CREATE TABLE PLO (
    MaPLO VARCHAR(10) PRIMARY KEY,
    TenPLO VARCHAR(10),
    MoTaPLO VARCHAR(255),
    MaCN VARCHAR(10),
    FOREIGN KEY (MaCN) REFERENCES CHUYENNGANH(MaCN)
);

-- Bang PI
CREATE TABLE PI (
    TenPI VARCHAR(10),
    MoTaPI VARCHAR(255),
    MaPLO VARCHAR(10),
    TenPLO VARCHAR(10),
	PRIMARY KEY (TenPI, MaPLO),
    FOREIGN KEY (MaPLO) REFERENCES PLO(MaPLO)
);

-- Bang PI_CLO_MAPPING
CREATE TABLE PI_CLO_MAPPING (
    TenPI VARCHAR(10),
	MaPLO VARCHAR(10),
    MaCLO VARCHAR(10),
    PRIMARY KEY (TenPI, MaCLO, MaPLO),
    FOREIGN KEY (TenPI, MaPLO) REFERENCES PI(TenPI,MaPLO),
    FOREIGN KEY (MaCLO) REFERENCES CLO(MaCLO)
);


-- Bang KETQUACLO
CREATE TABLE KETQUACLO (
    MaCLO VARCHAR(10),
    MaSV VARCHAR(12),
    MaLopHP VARCHAR(10),
    DiemCLO FLOAT,
    MucDat VARCHAR(20),
    PRIMARY KEY (MaCLO, MaSV, MaLopHP),
    FOREIGN KEY (MaCLO) REFERENCES CLO(MaCLO),
    FOREIGN KEY (MaSV, MaLopHP) REFERENCES DANGKYHOCPHAN(MaSV,MaLopHP),
);

-- Bang KETQUAPLO
CREATE TABLE KETQUAPLO (
    MaSV VARCHAR(12),
    MaPLO VARCHAR(10),
    DiemPLO FLOAT,
    MucDat VARCHAR(20),
    NienKhoa VARCHAR(20),
    PRIMARY KEY (MaSV, MaPLO),
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV),
    FOREIGN KEY (MaPLO) REFERENCES PLO(MaPLO)
);

-- Bang KHAOSAT
CREATE TABLE KHAOSAT (
    MaSV VARCHAR(12),
    MaPLO VARCHAR(10),
    DiemDG INT,
    MucDat VARCHAR(20),
    PRIMARY KEY (MaSV, MaPLO),
    FOREIGN KEY (MaPLO) REFERENCES PLO(MaPLO),
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV)
);
